version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '01:23'
      timezone: Europe/Warsaw
    labels:
      - dependencies
      - actions
    groups:
      # name of the group
      exposed:
        patterns:
          - 'org.jetbrains.exposed:*'
  - package-ecosystem: gradle
    directory: /server
    schedule:
      interval: daily
      time: '01:23'
      timezone: Europe/Warsaw
    labels:
      - dependencies
      - libs
      - server
