version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '01:23'
      timezone: Europe/Warsaw
    labels:
      - dependencies
      - actions
  - package-ecosystem: gradle
    directory: /server
    schedule:
      interval: daily
      time: '01:23'
      timezone: Europe/Warsaw
    labels:
      - dependencies
      - libs
      - server
    groups:
      exposed:
        patterns:
          - 'org.jetbrains.exposed:*'
      kotlin:
        patterns:
          - 'jvm'
          - 'plugin.spring'
          - 'plugin.jpa'
  - package-ecosystem: gradle
    directory: /client
    schedule:
      interval: daily
      time: '01:23'
      timezone: Europe/Warsaw
    labels:
      - dependencies
      - libs
      - client
    groups:
      exposed:
        patterns:
          - 'org.jetbrains.exposed:*'
      kotlin:
        patterns:
          - 'jvm'
          - 'plugin.spring'
          - 'plugin.jpa'
