
spring:
  jpa:
    # https://stackoverflow.com/a/48222934
    open-in-view: false
  datasource:
    # http://h2database.com/html/features.html#other_logging
    url: jdbc:h2:mem:mydb;TRACE_LEVEL_FILE=4
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

logging:
  level:
    ROOT: INFO
    org.h2: WARN
