name: OWASP dependency check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '19 19 * * *'

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: "${{ secrets.NVD_API_KEY }}"
    steps:
      - name: Info
        run: 'echo "Running OWASP check on branch: ${{ inputs.currentBranchName }}"'
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Zulu/Azul JAVA 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Cache for OWASP Vulnerabilities
        id: cache-owasp-vulnerability-database
        uses: actions/cache@v4
        if: always()
        with:
          key: cache-owasp-vulnerability-database
          path: .gradle/dependency-check-data/9.0
      - name: Check env variable
        run: >
          if [[ -z "${NVD_API_KEY}" ]]; then
            echo "[FAILURE] Missing NVD_API_KEY env variable" && exit 1
          else
            echo "[SUCCESS] NVD_API_KEY env variable exists"
          fi
      - name: Check Security Vulnerabilities
        run: ./gradlew dependencyCheckAggregate
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-reports-${{ github.run_id }}
          path: ./build/reports
          overwrite: true
          retention-days: 7
