name: OWASP dependency check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 5,16 * * *'

jobs:
  owasp-dependency-cache:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Zulu/Azul JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache OWASP Vulnerabilities
        id: cache-owasp-vulnerability-database
        uses: actions/cache@v3
        with:
          key: cache-owasp-vulnerability-database
          path: ~/.gradle/dependency-check-data/7.0
      - name: Update Security Vulnerabilities
        run: ./gradlew dependencyCheckUpdate

  owasp-dependency-check:
    runs-on: ubuntu-latest
    needs:
      - owasp-dependency-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Zulu/Azul JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Restore Cache for OWASP Vulnerabilities Database
        uses: actions/cache/restore@v3
        with:
          key: cache-owasp-vulnerability-database
          path: ~/.gradle/dependency-check-data/7.0
          fail-on-cache-miss: true
      - name: Check Security Vulnerabilities
        run: ./gradlew dependencyCheckAnalyze
