name: OWASP dependency check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron: '07 07 * * *'
#    - cron: '14 14 * * *'
    - cron: '19 19 * * *'
  workflow_call:
    inputs:
      currentBranchName:
        description: 'Current branch on which the OWASP check is run'
        type: string
        default: 'main'
    secrets:
      NVD_API_KEY:
        description: 'NVD API key for owasp dependency check plugin'
        required: true

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: "${{ secrets.NVD_API_KEY }}"
    steps:
      - name: Info
        run: 'echo "Running OWASP check on branch: ${{ inputs.currentBranchName }}"'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Zulu/Azul JAVA 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache for OWASP Vulnerabilities
        id: cache-owasp-vulnerability-database
        uses: actions/cache@v4
        with:
          key: cache-owasp-vulnerability-database
          path: ~/.gradle/dependency-check-data/7.0
      - name: Check env variable
        run: >
          if [[ -z "${NVD_API_KEY}" ]]; then
            echo "Missing NVD_API_KEY env variable"
          else
            echo "NVD_API_KEY env variable exists"
          fi
      - name: Check Security Vulnerabilities
        run: ./gradlew dependencyCheckAnalyze
